name: untitled8
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_animate:
  smooth_page_indicator:
  geolocator:
  latlong2: ^0.9.1
  vector_math:
  flutter_bloc:
  flutter_screenutil:
  flutter_svg:
  intl:
  hive:
  hive_flutter:
  http:
  url_launcher:
  persistent_bottom_nav_bar_v2:
  dropdown_button2:
  dartz:
  shared_preferences:
  flutter_launcher_icons:
  equatable:
  flutter_riverpod:
  fl_chart:
  image_picker:
  cupertino_icons: ^1.0.8
  path_provider:
  collection:
  dio:
  json_annotation:
  connectivity_plus:
  flutter_secure_storage:
  flutter_local_notifications:
  get_it:
  firebase_core:
  firebase_messaging:
  firebase_auth:
  cloud_firestore:
  pdf:
  printing:
  flutter_map: ^7.0.2
  location: ^8.0.1
  internet_connection_checker: ^3.0.1
  shimmer: ^3.0.0
  logger: ^2.6.2
  injectable: ^2.4.2
  bot_toast: ^4.1.3
  flutter_cache_manager: ^3.3.0
  awesome_notifications: ^0.11.0
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  injectable_generator: ^2.4.1
  flutter_gen_runner: 5.3.2
  hive_generator:
  json_serializable:
  flutter_lints:


flutter_gen:
  output: lib/common/design/src/theme/
  integrations:
    lottie: true

flutter_native_splash:
  color: "#F8F9FA"
  image: assets/image/png/native_splash/native_splash.png
  #    branding: assets/images/branding.png
  android_12:
    image: assets/image/png/native_splash/native_splash12.png
    icon_background_color: "#F8F9FA"
  web: false


# ðŸ”¹ Ø¥Ø¹Ø¯Ø§Ø¯Ø§Øª Ø£ÙŠÙ‚ÙˆÙ†Ø© Ø§Ù„ØªØ·Ø¨ÙŠÙ‚ Ø§Ù„Ø¬Ø¯ÙŠØ¯Ø© (ØªÙ… ØªØ­Ø¯ÙŠØ« Ø§Ù„Ø§Ø³Ù… Ù„Ù€ logoapp.png)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/image/log/logoapp.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/image/gif/
    - assets/image/log/
#    - assets/icons/
